category: "pushpins"
train_image_path: "C:/Users/kev30/Desktop/anomaly/EfficientAD-res/datasets/mvtec_loco_anomaly_detection/category/train/good/*.png"
test_image_path: "C:/Users/kev30/Desktop/anomaly/EfficientAD-res/datasets/mvtec_loco_anomaly_detection/category/test/*/*.png"
val_image_path: "C:/Users/kev30/Desktop/anomaly/EfficientAD-res/datasets/mvtec_loco_anomaly_detection/category/validation/*/*.png"
mask_root: "C:/Users/kev30/Desktop/anomaly/EfficientAD-res/datasets/masks/category"
model_path: "C:/Users/kev30/Desktop/anomaly/EfficientAD-res/ckpt/segmentor_category.pth"
fill_holes: False
in_dim: [256,1024]
orig_image_size: [1000,1700]
load: False
image_size: 256
lr: 0.01
epoch: 100 # 20
sup_only_epoch: 50 # 15
LSA_ratio: 0.5
SSA_ratio: 0.0
loss_weight: 
    ce: 0.5 # 0.1
    focal: 10
    dice: 1
    hist: 10
    entropy: 1

LSA_config: 
    min_distance: 0.2
    max_aug_num: 2
    min_aug_num: 1
    boundary: 0.1
    weight_power: 0.0